#!/usr/bin/python3
# textwrap - wrap long lines to fit on the screen
# Copyright (C) 2012  Jakob Kramer <jakob.kramer@gmx.de>
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

try:
    import struct

    from fcntl import ioctl
    from termios import TIOCGWINSZ
except ImportError:
    detection_support = False
else:
    detection_support = True

from sys import stdin, stdout
from textwrap import fill
from argparse import ArgumentParser

WIDTH = 79

def terminal_size():
    'Return a (height, width) pair for standard output.'
    return struct.unpack('HHHH', ioctl(stdout.fileno(), TIOCGWINSZ,
                                       struct.pack('HHHH', 0, 0, 0, 0)))[:2]


def parse_arguments():
    if detection_support and stdout.isatty():
        height, width = terminal_size()
        if width > WIDTH:
            width = WIDTH
    else:
        width = WIDTH

    parser = ArgumentParser(description='Wrap long lines to fit on the screen '
                            'with proper line breaks and print them on '
                            'standard output.')

    parser.add_argument('-w', '--width', type=int, default=width,
                        help='Specifies how long the lines are supposed to '
                        'be.  By default this is the width of the open '
                        'terminal or {width} on normal output files or '
                        'unsupported systems.  If the terminal has more than '
                        '{width} columns, the width defaults to '
                        '{width}.'.format(width=WIDTH))

    parser.add_argument('filename', metavar='FILE', default='-', help='File to '
                        'be wrapped.  Use "-" for standard input. (default: -)',
                        nargs='?')

    return parser, parser.parse_args()


def fill_multi(text, **kwargs):
    'Wrap multiple lines of text.  `text` is an iterator over the input lines.'
    return '\n'.join(fill(line, **kwargs) for line in text.splitlines())


def main():
    parser, args = parse_arguments()

    try:
        f = args.filename == '-' and stdin or open(args.filename)
        print(fill_multi(f.read(), width=args.width))
        f.close()
    except Exception as e:
        parser.error(e)


if __name__ == '__main__':
    main()
